# -*- coding: utf-8 -*-
"""Bar_PLot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Shrinivas18/7f21e77714d453a849afb56687b804ef/untitled6.ipynb
"""

import matplotlib.pyplot as plt
import numpy as np

"""**Single Bar Graph**"""

x=["Python","C","C++","Java"]
y=[95,70,60,92]
colors=["g","r","m","y"]

plt.xlabel("Languages",fontsize=10)
plt.ylabel("Percentage",fontsize=10)
plt.title("Bar Graph",fontsize=20)

plt.bar(x,y,color=colors,width=0.5,linewidth=5,label="h")
plt.legend(loc="upper center")
plt.show()