# -*- coding: utf-8 -*-
"""Box_and_Whisker_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Box and Whisker plot**"""

x=[10,20,30,40,50,60,70,120]

plt.boxplot(x, labels=["python"], patch_artist=True, showmeans=True, notch=True,
            whis=2)  # Whisker calue ranges upto 1.5 times the interquartile range.
plt.title("Box and Whisker Plot")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.show()