# -*- coding: utf-8 -*-
"""Donut_Pie_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Donut Pie Chart**"""

import matplotlib.pyplot as plt
plt.pie([1],colors='r')
plt.title("Donut_Pie_Plot")
plt.show()