# -*- coding: utf-8 -*-
"""Pie_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**PIE CHART**"""

import matplotlib.pyplot as plt
import numpy as np

x=[20,30,50,55]
y=['C','C++','Java','Python']
c=['r','b','g','y']
ex=[0.4,0.1,0.0,0.0]
plt.pie(x,labels=y,colors=c,explode=ex,autopct="%0.1f%%",startangle=0,textprops={"fontsize":12,"color":'black'},counterclock=False
        ,wedgeprops={"linewidth":0,"edgecolor":'g'},shadow=True,rotatelabels=False)
plt.legend(loc=2,fontsize=7)
plt.show()