# -*- coding: utf-8 -*-
"""Ring_Pie_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Ring Pie Plot**"""

x=[10,20,30,40]
x1=[30,40,10,20]
y=['C','C++','Java','Python']
c=['r','g','y','m']
plt.pie(x,labels=y,radius=1.5,colors=c)
plt.pie([1],radius=1,colors='w')
plt.title("Ring-Pie Plot",fontsize=20,pad=50)
plt.show()