# -*- coding: utf-8 -*-
"""Scatter_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Scatter Plot**"""

x=[80,40,50,70]
y=[95,70,60,92]
z=[20,40,50,80]
sizes=[200,300,400,500]
colors=["g","r","m","y"]

plt.scatter(x,y,color='r',s=sizes,marker="*",linewidth=0.8,edgecolor='b')
plt.scatter(x,z,color='b',s=sizes,linewidth=0.8)
plt.show()

# Multi Scatter plot below