# -*- coding: utf-8 -*-
"""Stack_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Stack Plot**"""

x=[1,2,3,4,5]
area1=[4,3,5,6,3]
area2=[2,3,1,4,5]
area3=[1,3,4,2,1]

l=["area1","area2","area3"]

plt.stackplot(x,area1,area2,area3,labels=l,colors=['r','g','m'] , baseline= "zero") # Other baseline are "sym" and "wiggle"
plt.legend(loc=2)
plt.title("Stack Plot")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")

plt.show()