# -*- coding: utf-8 -*-
"""Stem_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fIEtZSyCTGi5Ev8R3975BFWNrlwBFmI
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Stem Plot**"""

x=[1,2,3,4,5,6]
y=[2,2,5,6,4,3]

plt.stem(x,y)
plt.title("Stem Plot")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.show()